language: python
python: 3.6

install:
- pip install -r requirements.txt

script:
- ./scripts/build-site.sh
- ls -R _site

deploy:
- provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  local-dir: "_site"
  verbose: true

